services:
  app:
    container_name: balloon-tomb-site
    build:
      context: ./site
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      # Take site directory and mount at app/ inside container
      - ./site:/app
      - /app/node_modules
      # Create an audio folder inside project
      - ./audio:/app/audio
    env_file:
      - .env.local
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: balloon-tomb-db
    env_file:
      - .env.local
    image: postgres:16-alpine
    # host port is 5433, container port is 5432
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:9.8
    ports:
      - 5050:80
    environment:
      # Required by pgAdmin
      PGADMIN_DEFAULT_EMAIL: oliverkiranbrown@gmail.com
      PGADMIN_DEFAULT_PASSWORD: something_very_secure

      # Don't require the user to login
      PGADMIN_CONFIG_SERVER_MODE: 'False'

      # Don't require a "master" password after logging in
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

# Is this persistant storage?
volumes:
  postgres_data:
