services:
  app:
    build:
      context: ./site
      dockerfile: Dockerfile.prod
    env_file:
      - .env.prod
    # temp fix to work (expose port to VPS inside continer)
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - audio_data:/app/audio
    depends_on:
      - db
    restart: unless-stopped

  admin-provision:
    build: 
      context: ./site
      dockerfile: Dockerfile.prod
    command: npx tsx scripts/create_admins.ts
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: "no"

  db:
    image: postgres:16-alpine
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./db-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
  audio_data: